### ISSUE TITLE
AKS C# Sample Fails with ServicePrincipalNotFound

### ISSUE THREAD

**Issue by swgriffith** [pulumi/examples#1026]
Trying to deploy an AKS cluster with Pulumi using C#, and there's an issue due to Service Principal propagation time. The cluster tries to create before the sp is ready. 

This is a common issue with infra as code solutions that we can typically address via including a sleep, or just ditching service principal for system assigned managed identity. I'll probably go with the latter, but would love to figure out how to properly implement a sleep, and understand if this is something that can be addressed in the provider itself (i.e. transient fault handling on the ServicePrincipalProfile object.

## Steps to reproduce
1. Just follow the steps outlined here: https://www.pulumi.com/docs/tutorials/azure/azure-cs-aks/

Expected: Cluster successfully created

Actual: 
  azure-native:containerservice:ManagedCluster (my-aks):
    error: Code="ServicePrincipalNotFound" Message="Service principal clientID: XXXX-XXXX-XXXX not found in Active Directory tenant XXXX-XXXX-XXXX, Please see https://aka.ms/aks-sp-help for more details."
 
  pulumi:pulumi:Stack (azure-cs-aks-dev):
    Waiting 3000m for SP to propagate.
 
    error: update failed
 
  azuread:index:ServicePrincipalPassword (aksSpPassword):
    warning: urn:pulumi:dev::azure-cs-aks::azuread:index/servicePrincipalPassword:ServicePrincipalPassword::aksSpPassword verification warning: Deprecated Attribute

**Comment by leezen** [comment]
@swgriffith If you wanted, you could introduce a sleep via an apply on the output for when you use the service principal as an input to another resource. I don't think there's a way to actually determine propagation, so I don't think this is an issue with the provider/example itself, so I'll close the issue.
