### ISSUE TITLE
New GCP Tutorial Request

### ISSUE THREAD

**Issue by mohamedhassan81** [pulumi/examples#1038]

**Comment by stack72** [comment]
Closing this as there is no details on what the request is

**Comment by mohamedhassan81** [comment]
The request is GCP tutorial videos or anything in that respect.Thanks 


Sent from Yahoo Mail for iPhone


On Tuesday, July 6, 2021, 6:11 AM, Paul Stack ***@***.***> wrote:




Closing this as there is no details on what the request is

**Comment by stack72** [comment]
Hi @mohamedhassan81 

in this repository you will see folders prefixed as `gcp-` - those are the language variants of google tutorials - hope this helps

**Comment by mohamedhassan81** [comment]
Thanks Paul, that will help!


Sent from Yahoo Mail for iPhone


On Tuesday, July 6, 2021, 6:17 AM, Paul Stack ***@***.***> wrote:




Hi @mohamedhassan81

in this repository you will see folders prefixed as gcp- - those are the language variants of google tutorials - hope this helps
