### ISSUE TITLE
Convert Go Azure examples to fnOutput form

### ISSUE THREAD

**Issue by t0yv0** [pulumi/examples#1115]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

https://github.com/pulumi/pulumi/issues/5758 permits more elegant composition of datasources and resources, however there are no examples. IN https://github.com/pulumi/examples/pull/1094 we swept through existing examples but the only ones that were found in Go that would benefit from the new feature utilize pulumi-azure-native. Unfortunately, the feature is not rolled out to the Go build of pulumi-azure-native yet to minimize generated code size and avoid hitting some limits. Therefore the examples update is blocked.

**Comment by mikhailshilkov** [comment]
@t0yv0 This should be unblocked now with azure-native v1.53.0.

**Comment by t0yv0** [comment]
Let's close this one is done.
