### ISSUE TITLE
Template Deployment examples consistently failing

### ISSUE THREAD

**Issue by leezen** [pulumi/examples#1138]
`classic-azure-py-arm-template` and `classic-azure-ts-arm-template` have been consistently failing where they timeout on destroying the template deployment

**Comment by stack72** [comment]
@leezen I will spend the morning tomorrow investigating this as this is causing us pain

**Comment by leezen** [comment]
I think the underlying issue here is the issue referenced in pulumi/pulumi-azure#1001

**Comment by leezen** [comment]
From an examples perspective, since `TemplateDeployment` is deprecated per the upstream documentation, I wonder if we should just swap the example to `ResourceGroupTemplateDeployment`. I'm going to try that to see if it unblocks tests (and would make for a better example anyway). If that works, I'll open a PR to resolve this issue. Assuming it does, we'll still want to keep pulumi/pulumi-azure#1001 open since it tracks fixing the `TemplateDeployment` resource.
