### ISSUE TITLE
Contributions for AWS?

### ISSUE THREAD

**Issue by s-dschro** [pulumi/examples#1178]
Hey guys,

I really love this project and would like to contribute. :)
Are there any open topics for AWS where you would still need any samples?

**Comment by guineveresaenger** [comment]
Hi @s-dschro!

Welcome to Pulumi!

I ran a [quick search for aws + example](https://github.com/pulumi/examples/issues?q=is%3Aissue+is%3Aopen+example+aws) in our open issues list and would welcome you to add any that seem good to you.

Please go ahead and read the [contributor guide](https://github.com/pulumi/examples/blob/master/CONTRIBUTING.md) and adhere to the [code of conduct](https://github.com/pulumi/examples/blob/master/CODE-OF-CONDUCT.md) before you get started. 😄 

Also - if you haven't joined the [Pulumi community slack](https://slack.pulumi.com/) yet, go ahead and join!

I'm going to close this for now so it doesn't clog up our triage backlog.
