### ISSUE TITLE
New GCP Tutorial Request - Host React App

### ISSUE THREAD

**Issue by bionicles** [pulumi/examples#1183]
### Problem description

- I had trouble finding the information that I needed: <URL>
There is no guide to launch a static site on GCP

### Suggestions for a fix

GC Storage, and some DNS

**Comment by algoflows** [comment]
Agreed!!! Trying to get a react app deployed to a GCP storage bucket, there is no information anywhere. Best practices? Do we need load balancers? The list of questions goes on... Adoption will grow if we can get frequent and comprehensive tutorials.

**Comment by georgeportillo** [comment]
+1

**Comment by scottslowe** [comment]
I think that the recent addition of a couple of Google Cloud-centric architecture templates may address this issue. For example, see the `serverless-gcp-typescript` or the `container-gcp-typescript` architecture templates in the pulumi/templates repository: https://github.com/pulumi/templates

Although I referenced the TypeScript versions, templates for C#, Go, Python, and YAML are also present in the repository.

I'm going to go ahead and close this issue, but please reopen the issue if you feel like additional action or discussion is needed. Thank you!
