### ISSUE TITLE
Azure Container Apps C# example doesn't work

### ISSUE THREAD

**Issue by rogerdawson** [pulumi/examples#1219]
### What happened?

Tried to run the [Container Apps C# example](https://github.com/pulumi/examples/tree/master/azure-cs-containerapps) and it wouldn't build or run. I fixed the build and some runtime issues but I can't get the stage that creates the container app to succeed.

### Steps to reproduce

Build the example referenced above. It fails to build due to the 'KubeEnvironment.Type' not existing. The intellisense suggests it should be 'EnvironmentType' which does indeed fix the build issue. However, the actual deployment fails to create the environment with the error below: 

_error: Code="InternalServerError" Message="Internal server error occurred. Error validating expected pods status in the k8s cluster" Details=[{"Message":"Internal server error occurred. Error validating expected pods status in the k8s cluster"},{"Code":"InternalServerError"},{"ErrorEntity":{"Code":"InternalServerError","ExtendedCode":"51017","Message":"Internal server error occurred. Error validating expected pods status in the k8s cluster","MessageTemplate":"Internal server error occurred. {0}","Parameters":["Error validating expected pods status in the k8s cluster"]}}]_ 

After some investigation it appears we should no longer use 'KubeEnvironment' but instead should use 'ManagedEnvironment' as shown below:

`var kubeEnv = new AzureNative.App.ManagedEnvironment("env", new AzureNative.App.ManagedEnvironmentArgs
        {
            AppLogsConfiguration = new AzureNative.App.Inputs.AppLogsConfigurationArgs
            {
                Destination = "log-analytics",
                LogAnalyticsConfiguration = new AzureNative.App.Inputs.LogAnalyticsConfigurationArgs
                {
                    CustomerId = workspace.CustomerId,
                    SharedKey = workspaceSharedKeys.Apply(r => r.PrimarySharedKey)
                },
            },
            Name = "env",
            ResourceGroupName = resourceGroup.Name,
            ZoneRedundant = false,
        });`

Tried redeploying and all the resources continue to be deployed, including the environment this time, but I got a failure stating container app APIs are not enabled when it tried to create the container app:

error: Code="NotFound" Message="ContainerApps APIs are not enabled." Details=[{"Message":"ContainerApps APIs are not enabled."},{"Code":"NotFound"},{"ErrorEntity":{"Code":"NotFound","ExtendedCode":"67003","Message":"ContainerApps APIs are not enabled.","MessageTemplate":"ContainerApps APIs are not enabled.","Parameters":[]}}] 

I tried both East US 2 and West Europe regions.

I created a container app successfully using the Azure CLI. I did note that the MS notes on creating container apps required an extension package and changing a namespace as explained [here](https://docs.microsoft.com/en-us/azure/container-apps/get-started?tabs=bash) but even with these changes Pulumi failed to create the container app.

### Expected Behavior

The container app would get created.

### Actual Behavior

An error stating 'Container App APIs are not enabled' was displayed as shown below:

`error: Code="NotFound" Message="ContainerApps APIs are not enabled." Details=[{"Message":"ContainerApps APIs are not enabled."},{"Code":"NotFound"},{"ErrorEntity":{"Code":"NotFound","ExtendedCode":"67003","Message":"ContainerApps APIs are not enabled.","MessageTemplate":"ContainerApps APIs are not enabled.","Parameters":[]}}] `

### Versions used

CLI
Version      3.32.1
Go Version   go1.17.9
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.64.0
docker        3.2.0
dotnet        unknown

Host     
OS       Microsoft Windows 11 Pro
Version  10.0.22000 Build 22000
Arch     x86_64

This project is written in dotnet (C:\Program Files\dotnet\dotnet.exe v6.0.202)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @rogerdawson - thank you for reporting! 

It turns out that you're running into a namespace migration in Azure and we failed to update the example accordingly. 

While we're fixing the example, we hope this discussion will help you get unstuck: https://github.com/pulumi/pulumi/discussions/9099
