### ISSUE TITLE
Create a sample that demonstrates how to use ParameterStore

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/examples#122]
Customer contacted us on slack with questions about how to properly do secrets, and how they would like to use ParameterStore to acquire that stuff at runtime.  It would likely be useful for many customers who use this system as per AWS's best practices recommendations.

**Comment by lukehoban** [comment]
https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/ssm/#Parameter
