### ISSUE TITLE
EKS Fargate Example

### ISSUE THREAD

**Issue by pmantica3** [pulumi/examples#1255]
## Hello!

It would be nice to have an example of AWS EKS Fargate Cluster. There are some examples in which individual components are provisioned through Fargate. But it would nice if we had one example in which any pod provisioned by a cluster is provisioned through Fargate.

**Comment by ericrudder** [comment]
Have you seen the material on https://www.pulumi.com/blog/aws-eks-managed-nodes-fargate/ ?

**Comment by pmantica3** [comment]
I hadn't. Thanks!

**Comment by ericrudder** [comment]
Great, if you have any questions, you can reach out on https://pulumi-community.slack.com/ in the #aws channel too.
