### ISSUE TITLE
upgrading pom with latest versions fails gcp gke example

### ISSUE THREAD

**Issue by nagkumar** [pulumi/examples#1273]
### What happened?

https://github.com/pulumi/examples/blob/master/gcp-java-gke-hello-world/pom.xml

![image](https://user-images.githubusercontent.com/332234/188615126-b2b1d110-c3ca-4305-9253-74c9251037cc.png)

upgrading to above version, the gke example fails

### Steps to reproduce

upgrade pom.xm and run the example

### Expected Behavior

upgrade should still work

### Actual Behavior

rem failed when upgraded the jars to
G:\DWork\osource\cloudc\devops\pulumi\java\gcp\gke>pu
Previewing update (dev)

View Live: https://app.pulumi.com/nagkumar/gcp-java-gke-hello-world/dev/previews/5807c277-65a0-4fec-b006-1bc668793c41

     Type                              Name                          Plan
+   pulumi:pulumi:Stack               gcp-java-gke-hello-world-dev  create
+   ├─ gcp:container:Cluster          helloworld                    create
+   ├─ gcp:container:NodePool         primary-node-pool             create
+   ├─ pulumi:providers:kubernetes    helloworld                    create
+   ├─ kubernetes:core/v1:Namespace   helloworld                    create
+   ├─ kubernetes:core/v1:Service     helloworld                    create
    servicePublicIP: output<string>

Resources:
+ 7 to create

Updating (dev)

View Live: https://app.pulumi.com/nagkumar/gcp-java-gke-hello-world/dev/updates/9

     Type                             Name                          Status                  Info
+   pulumi:pulumi:Stack              gcp-java-gke-hello-world-dev  **creating failed**     1 error; 3 messages
+   ├─ gcp:container:Cluster         helloworld                    created
+   ├─ gcp:container:NodePool        primary-node-pool             created
+   ├─ pulumi:providers:kubernetes   helloworld                    created
+   └─ kubernetes:core/v1:Namespace  helloworld                    **creating failed**     1 error

Diagnostics:
pulumi:pulumi:Stack (gcp-java-gke-hello-world-dev):
W0906 15:31:59.782230    5612 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
E0906 15:32:42.096155    5612 request.go:977] Unexpected error when reading response body: net/http: request canceled (Client.Timeout or context cancellation while reading body)

    error: update failed

kubernetes:core/v1:Namespace (helloworld):
error: configured Kubernetes cluster is unreachable: unable to load schema information from the API server: unexpected error when reading response body. Please retry. Original error: net/http: request canceled (Client.Timeout
or context cancellation while reading body)

Resources:
+ 4 created

Duration: 8m28s

### Output of `pulumi about`

G:\DWork\osource\cloudc\devops\pulumi\java\gcp\gke>pulumi about
CLI
Version      3.39.1
Go Version   go1.19
Go Compiler  gc

Plugins
NAME        VERSION
gcp         6.36.0
java        unknown
kubernetes  3.22.0-alpha.1662065558+2eb06f38

Host
OS       Microsoft Windows 10 Pro
Version  10.0.19045 Build 19045
Arch     x86_64

This project is written in java: executable='d:\Apps\Dev\langs\java\jdk\17.x\bin\java.exe' version='java 17.0.2 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)' javac='17.0.2' java='d:\Apps\Dev\langs\java\jdk\17.x\bin\java.exe'

Current Stack: dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/nagkumar
User           nagkumar
Organizations  nagkumar, tejasoft

No dependencies found

Pulumi locates its logs in C:\Users\RAJANA~1\AppData\Local\Temp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by viveklak** [comment]
@nagkumar thanks for opening the issue. I assume the state on the left is the "updated" state for pom.xml? Are you creating the stack from scratch based on the pinned versions or updating an existing stack after pinning the versions?

**Comment by viveklak** [comment]
FWIW I tried both scenarios above and didn't run into the problem. Is this happening consistently for you? Perhaps the cluster is no longer accessible/has been terminated?
