### ISSUE TITLE
AWS examples containing SecurityGroups need VPC and Subnet

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/examples#1283]
As of the [upstream v4.30.0 pulumi-aws provider](https://github.com/pulumi/pulumi-aws/issues/2130), EC2 Classic is completely unsupported.

This caused pulumi-aws integrations tests for webservers to [fail](https://github.com/pulumi/pulumi-aws/actions/runs/3046842616/jobs/4910585900#step:22:226) with the following message:

```
aws:ec2:SecurityGroup (web-secgrp):
      error: 1 error occurred:
      	* with the retirement of EC2-Classic no new Security Groups can be created without referencing a VPC
```

It will affect any examples here that attempt to bring up a webserver on an EC2 instance without a VPC for its security group, which may be any of the following:

- https://github.com/pulumi/examples/tree/master/aws-cs-webserver
- https://github.com/pulumi/examples/blob/master/aws-go-webserver
- https://github.com/pulumi/examples/tree/master/aws-js-webserver-component
- https://github.com/pulumi/examples/tree/master/aws-js-webserver
- https://github.com/pulumi/examples/tree/master/aws-java-webserver
- https://github.com/pulumi/examples/tree/master/aws-py-webserver
- https://github.com/pulumi/examples/tree/master/aws-ts-webserver

**Comment by stack72** [comment]
@guineveresaenger as they are rolling this back - should we close this out?

**Comment by guineveresaenger** [comment]
This was fixed upstream.
