### ISSUE TITLE
gcp-ts-functions doesn't work

### ISSUE THREAD

**Issue by vbo75** [pulumi/examples#1294]
### What happened?

Hi,
I working on a onepage JS app with REST API backend storage. I want to deploy this app in a full serverless GC config with Pulumi. So I'm testing your sample https://www.pulumi.com/blog/simple-serverless-programming-with-google-cloud-functions-and-pulumi/ and https://github.com/pulumi/examples/blob/master/gcp-ts-functions/index.ts

### Steps to reproduce

Here is the the code that I wrote. Because of intempestive errors with Typescript support (error TS2339: Property 'send' does not exist on type 'Response<any, Record<string, any>>'), I changed to Javascript support.

```
var gcp = require("@pulumi/gcp")

const runtime = "nodejs16";
const endpoint = new gcp.cloudfunctions.HttpCallbackFunction("backend", {
    runtime: runtime,
    callback: (req, res) => {
        console.log('Log say Hello');
        res.send('Hello');
    }
});

const invoker = new gcp.cloudfunctions.FunctionIamMember("invoker", {
    project: endpoint.function.project,
    region: endpoint.function.region,
    cloudFunction: endpoint.function.name,
    role: "roles/cloudfunctions.invoker",
    member: "allUsers",
});

exports.url = endpoint.httpsTriggerUrl;
```

### Expected Behavior

$ curl "$(pulumi stack output url)"
=> Hello

$ pulumi logs --follow
=> Log say Hello

### Actual Behavior

Nothing in command line
Nothing in logs

### Output of `pulumi about`

CLI
Version      3.42.0
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME    VERSION
gcp     6.40.0
nodejs  unknown

Host
OS       darwin
Version  12.6
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v16.15.0'

Current Stack: dev

TYPE                                                    URN
pulumi:pulumi:Stack                                     urn:pulumi:dev::archimodel-backend::pulumi:pulumi:Stack::archimodel-backend-dev
gcp:cloudfunctions:CallbackFunction                     urn:pulumi:dev::archimodel-backend::gcp:cloudfunctions:CallbackFunction::backend
pulumi:providers:gcp                                    urn:pulumi:dev::archimodel-backend::pulumi:providers:gcp::default_6_40_0
gcp:storage/bucket:Bucket                               urn:pulumi:dev::archimodel-backend::gcp:cloudfunctions:CallbackFunction$gcp:storage/bucket:Bucket::backend
gcp:storage/bucketObject:BucketObject                   urn:pulumi:dev::archimodel-backend::gcp:cloudfunctions:CallbackFunction$gcp:storage/bucketObject:BucketObject::backend
gcp:cloudfunctions/function:Function                    urn:pulumi:dev::archimodel-backend::gcp:cloudfunctions:CallbackFunction$gcp:cloudfunctions/function:Function::backend
gcp:cloudfunctions/functionIamMember:FunctionIamMember  urn:pulumi:dev::archimodel-backend::gcp:cloudfunctions:CallbackFunction$gcp:cloudfunctions/functionIamMember:FunctionIamMember::backend-invoker
gcp:cloudfunctions/functionIamMember:FunctionIamMember  urn:pulumi:dev::archimodel-backend::gcp:cloudfunctions/functionIamMember:FunctionIamMember::invoker

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/vbo75
User           vbo75
Organizations  vbo75

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.42.0
@types/express  4.17.14
@types/node     14.18.32
@pulumi/gcp     6.40.0

Pulumi locates its logs in /var/folders/9s/g35d2pv16tbg3y3j1cssvtlh0000gn/T/ by default

### Additional context

When I past url to navigator, I've got an Error: Forbidden Your client does not have permission to get URL /backend-69df273 from this server.
I think it's because Google security disallow public access without --allow-unauthenticated property but I don't know how to set this property in Pulumi. (https://cloud.google.com/functions/docs/tutorials/http).
But I don't understand why there is no log entry. Thanks for your help

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
removing `needs-triage`, will be triaged independently

**Comment by cnunciato** [comment]
It looks like this is a problem with the underlying GCP provider; the typings don't work even on a new `gcp-typescript` project. I'll file an issue there.

**Comment by cnunciato** [comment]
Filed https://github.com/pulumi/pulumi-gcp/issues/939.

Leaving this issue open for the time being, as we may just want to patch this example with `:any`s depending what happens with ☝️ that issue.
