### ISSUE TITLE
[Tutorial][Yandex] Request to show how to create a Kubernetes cluster on Yandex Cloud

### ISSUE THREAD

**Issue by bektineyev** [pulumi/examples#1299]
I ask you to make a new instruction for working with Pulumi Kubernetes Yandex Cloud:
Create:
- Pulumi Kubernetes Yandex Cloud (csharp, python, go)
- create cluster, create and add nodes

**Comment by scottslowe** [comment]
Hi @bektineyev! Thanks for opening this issue with your request. We'll put this in our backlog, but in the meantime we'd certainly be open to accepting any example you might be willing to create and submit.
