### ISSUE TITLE
Deprecate examples not using the EKS component?

### ISSUE THREAD

**Issue by scottslowe** [pulumi/examples#1314]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Now that AWSx has hit 1.0 and is GA, should we deprecate examples that don't use the EKS component? There are several examples in this repository, including (but not limited to) `aws-cs-eks`, `aws-py-eks`, and `aws-go-eks`, that do not use the AWSx EKS component (note that both `aws-ts-eks` and `aws-yaml-eks` use AWSx and the EKS component). Or do we feel there is still value in providing examples of creating EKS clusters _without_ the component?

### Affected area/feature

This only affects the `examples` repository.

**Comment by scottslowe** [comment]
Tagging @lukehoban @aaronkao @cnunciato for feedback

**Comment by roothorp** [comment]
Perhaps @danielrbradley can offer more insight here, but it's my understanding that if people are creating EKS clusters we want to encourage them to be using the EKS component. However, I can see the value in providing _some_ examples for creating EKS clusters with pulumi-aws (without the component).

**Comment by cnunciato** [comment]
>However, I can see the value in providing some examples for creating EKS clusters with pulumi-aws (without the component).

Me too. For some of these, though (especially those that are presented as canonical examples, as these `aws-*-eks` ones may be), we might want to get them updated to use AWSx. It looks like there may also be slight differences between what these particular examples are doing, so we might want to adjust them to get them aligned resource-wise (such that they're all deploying the same thing) while we're in there. I don't have strong feeling on this, though, but all else equal, I'd probably default to updating them (and their READMEs and referring docs, if any).

**Comment by scottslowe** [comment]
Consensus seems to be that we should have examples that use both the EKS component and pulumi-aws, so closing this issue as not planned.
