### ISSUE TITLE
stack readme link still 404ing

### ISSUE THREAD

**Issue by susanev** [pulumi/examples#1323]
in #1321 the link was updated, but that link still does not work

this is what its sending people to
https://www.pulumi.com/registry/packages/aws/how-to-guides/stack-readme-ts
now, which 404s

do yall know what this link is supposed to be?

i am not seeing the readme how-to guides population in registry
are they failing to be included based on other errors

looks like yes, they are all failing on..

```
warning: malformed tutorial name; expected <cloud>-<language>-<short-name>, got 'stack-readme-cs'
warning: malformed tutorial name; expected <cloud>-<language>-<short-name>, got 'stack-readme-go'
warning: malformed tutorial name; expected <cloud>-<language>-<short-name>, got 'stack-readme-java'
warning: malformed tutorial name; expected <cloud>-<language>-<short-name>, got 'stack-readme-py'
warning: malformed tutorial name; expected <cloud>-<language>-<short-name>, got 'stack-readme-ts'
warning: malformed tutorial name; expected <cloud>-<language>-<short-name>, got 'stack-readme-yaml'
```

will see if i can open a pr to fix that

**Comment by cnunciato** [comment]
@susanev Yeah, there are several examples like this one that don't really "go" with any one cloud provider or package, so they're basically left out of the mktutorial process.

Your 404 fix is good for now. We'll most likely be undertaking work next quarter that should give these left-out examples a proper home, so I don't think anything more need be done at this point for this issue.

**Comment by cnunciato** [comment]
Closing as completed with https://github.com/pulumi/examples/pull/1324.
