### ISSUE TITLE
Adopt new Redis terminology

### ISSUE THREAD

**Issue by joeduffy** [pulumi/examples#133]
Per https://twitter.com/antirez/status/1039443441472688128, Redis is changing its terminology from master/slave to master/replica. Let's proactively go through our various examples that use Redis -- like the Kubernetes guestbook -- and make these same changes.

**Comment by hausdorff** [comment]
This is a good idea. In other repositories I actually proactively called it master/agent (following in the footsteps of Mesos, which made a similar transition ~2 years ago). When we re-implemented all these examples for the examples repo, we ended up in where we are now out of carelessness: I wrote a small vscode extension to auto-transform YAML to Pulumi, and this was an artifact of that.

We should therefore fix it.
