### ISSUE TITLE
Java example uses deprecated data source

### ISSUE THREAD

**Issue by asaf400** [pulumi/examples#1335]
When using this example:
https://github.com/pulumi/examples/blob/563bf3a80b388c3bbe38c89a49edea56331cf0b0/aws-java-eks-minimal/src/main/java/com/pulumi/example/eksminimal/App.java#L27

Pulumi output includes this error:
```
warning: aws:ec2/getSubnetIds:getSubnetIds verification warning: The aws_subnet_ids data source has been deprecated and will be removed in a future version. Use the aws_subnets data source instead.
```

**Comment by abhinav** [comment]
Hi @asaf400, thanks for reporting this!
Fixing this in #1336.
