### ISSUE TITLE
AKS helm example error referencing apache resource

### ISSUE THREAD

**Issue by jjcollinge** [pulumi/examples#136]
The [AKS helm](https://github.com/pulumi/examples/tree/master/azure-ts-aks-helm) example tries to export the service IP using the following code:

```
export let serviceIP =
    (apache.resources["v1/Service::default/apache-apache"] as k8s.core.v1.Service).
        spec.apply(s => s.clusterIP);
```

This threw an error during preview as `apache.resources["v1/Service::default/apache-apache"]` was returning undefined. Once I removed the namespace 'default' from the key it worked ok and I got the correct output.  Before I submit a PR to remove it, I wanted to check this issue repro'd with others.

**Comment by hausdorff** [comment]
@jjcollinge thanks, you're probably right, I'll get that fixed ASAP because this line is outdated anyway. It should be something like:

```typescript
export let serviceIP = apache.getResource("v1/Service", "apache-apache").spec.apply(s => s.clusterIP);
```
