### ISSUE TITLE
Pulumi example that replaces AWS CodePipeline reference architecture

### ISSUE THREAD

**Issue by lindydonna** [pulumi/examples#14]
Show how this exact reference architecture maps to Pulumi: [Set Up a Continuous Delivery Pipeline for Containers Using AWS CodePipeline and Amazon ECS](https://aws.amazon.com/blogs/compute/set-up-a-continuous-delivery-pipeline-for-containers-using-aws-codepipeline-and-amazon-ecs/)

See also: https://github.com/awslabs/ecs-refarch-continuous-deployment

**Comment by lindydonna** [comment]
The blog post is complete, but it doesn't incorporate CI (see http://blog.pulumi.com/deploying-production-ready-containers-with-pulumi). A good follow up would be to show how to integrate it in a Travis workflow.

**Comment by mikhailshilkov** [comment]
@lukehoban Is this still something actionable or should we close?

**Comment by lukehoban** [comment]
We can close.
