### ISSUE TITLE
Default kubernetes version in example is unsupported

### ISSUE THREAD

**Issue by mnlumi** [pulumi/examples#1427]
### What happened?

The default version of kubernetes in the [azure-py-aks example](https://github.com/pulumi/examples/tree/master/azure-py-aks) is too old and no longer supported by Azure.
`‘kubernetes_version="1.18.14"`.

### Expected Behavior

I expect the default to be a supported version.

### Steps to reproduce

Run the azure-py-aks example. See the error about 1.18 not being supported.

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment]
I see 7 more places where this old unsupported version is used.  @mnlumi should we reopen this and also fix/test those?

https://github.com/search?q=repo%3Apulumi%2Fexamples%201.18.14&type=code

**Comment by mnlumi** [comment]
> I see 7 more places where this old unsupported version is used. @mnlumi should we reopen this and also fix/test those?
> 
> https://github.com/search?q=repo%3Apulumi%2Fexamples%201.18.14&type=code

@lukehoban I found a few more as well and submitted an additional PR. Thank you for calling this out!
