### ISSUE TITLE
CLI performance metrics examples broken due to AWS S3 security changes

### ISSUE THREAD

**Issue by justinvp** [pulumi/examples#1430]
See https://github.com/pulumi/examples/actions/runs/5090579201/jobs/9149574791#step:15:1

The following tests are failing with similar errors:

- TestAccAwsCsS3Folder
- TestAccAwsFsS3Folder
- TestAccAwsGoS3Folder
- TestAccAwsJsS3Folder
- TestAccAwsPyS3Folder
- TestAccAwsTsS3Folder

```
    aws:s3:BucketPolicy (bucketPolicy):
      error: 1 error occurred:
      	* Error putting S3 policy: AccessDenied: Access Denied
      	status code: 403, request id: MV0GQRM7F6H17R9Q, host id: kKyHGbCnBTbCoY5egn0d2tq6NO2iIxh18n0xGx6glx1oxrPjA0vZ/Ekd8BHFgt3B/vzYk5WrOFQ=
```

It looks like these examples need to be updated along the lines of:

- https://github.com/pulumi/pulumi-yaml/pull/451
- https://github.com/pulumi/pulumi-hugo/pull/2719

**Comment by cnunciato** [comment]
Fixed via #1470.
