### ISSUE TITLE
Fix Confusing ToC and add an intro to /docs/tutorials/kubernetes/gke/

### ISSUE THREAD

**Issue by isaac-pulumi** [pulumi/examples#1435]
## Problem
/docs/tutorials/kubernetes/gke/ has a high blended score (2158) for traffic, bounce rate and negative feedback.
The table of contents (right-hand nav) is confusing.  Fixes to this tutorial may be useful for other /tutorials.

## Proposed Solution

- [ ] Add a better intro paragraph: "in this tutorial, you'll learn..." 

- [ ] Experimentation is a bad heading for the ToC - suggest "Deploying Kubernetes Apps to Your GKE Cluster" instead.

**Comment by cnunciato** [comment]
Closing as we've no plans to update these, and they'll all be replaced with the completion of the Examples project.
