### ISSUE TITLE
Add Azure AKS Managed Identity example

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/examples#1501]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

**Comment by cnunciato** [comment]
Hey Phil, is this something you're planning to do, or just a suggestion? Either way's fine, just figured we'd ask in case you're already working on it.

**Comment by phillipedwards** [comment]
Yeah, I self-assigned it as I'm planning on handling this one myself.

**Comment by scottslowe** [comment]
@phillipedwards This issue can be closed, right? (addressed via https://github.com/pulumi/examples/pull/1524)

**Comment by phillipedwards** [comment]
Fixed by https://github.com/pulumi/examples/pull/1524
