### ISSUE TITLE
cloud-ts-url-shortener-cache-http example not returning valid payload

### ISSUE THREAD

**Issue by daveremy** [pulumi/examples#155]
Follow the readme steps for cloud-ts-url-shortener-cache-http.  When curling the endpoint an unexpected payload is returned (expecting real web page).

```
$ curl $(pulumi stack output endpointUrl)
{"uncaught":{"url":"/index.html","baseUrl":"","originalUrl":"/index.html","version":"v8.10.0"}}
```

**Comment by stack72** [comment]
I am going to track the work to fix this in #337
