### ISSUE TITLE
Test failing for `examples/aws-ts-lambda-efs`

### ISSUE THREAD

**Issue by desteves** [pulumi/examples#1634]
### What happened?

I have a PR with a new example being added; however, an existing example test is failing. I re-ran the job, but the error persists. Please investigate.

[Link to the test](https://github.com/pulumi/examples/actions/runs/8992678190/job/24702982203?pr=1633)

Error message snippet:
```* creating Lambda Function (uploadHandler-d8c65a4): operation error Lambda: CreateFunction, https response error StatusCode: 400, RequestID: 50ba4137-5c45-4e0f-852c-7a31bf2cf77a, InvalidParameterValueException: SubnetIds and SecurityIds must coexist or be both empty list.
```

### Example

`examples/aws-ts-lambda-efs`

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by sean1588** [comment]
Closing this out, since we have automation that auto opens issues for test failures that we keep tabs on.
