### ISSUE TITLE
GCP v8 Prerelease: Test against pulumi/examples

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/examples#1675]
Test the v8 prerelease on any GCP examples. Identify all examples using GCP v7 and update accordingly.

[Example pull request here](https://github.com/pulumi/examples/pull/1512).

**Comment by cnunciato** [comment]
@guin Are you planning to take this on yourself? Did you want any help from the devrel team on it?

**Comment by guineveresaenger** [comment]
@cnunciato this particular initiative mostly involves opening a PR and running the integration tests - but if there's other opportunities for pre-release testing I'd love some of that. 💟

**Comment by guineveresaenger** [comment]
Pull request is here: https://github.com/pulumi/examples/pull/1679. Will close when relevant tests are green.

**Comment by guineveresaenger** [comment]
Relevant tests are green. Digitalocean test failure unrelated. 🎉
