### ISSUE TITLE
Create an example for Azure Service Fabric

### ISSUE THREAD

**Issue by clstokes** [pulumi/examples#202]
https://azure.microsoft.com/en-us/services/service-fabric/

**Comment by stack72** [comment]
@clstokes I am going to suggest we close this out - Service Fabric doesn't seem as fashionable as it used to be

Thoughts?

**Comment by clstokes** [comment]
@stack72 closed.

**Comment by tedvanderveen** [comment]
@clstokes @stack72 please reopen this issue, an example for Azure Service Fabric would be great!
Not sure where that notion that Service Fabric is "not as fashionable as it used to be", any facts behind that statement is missing. What I do know is that most of Azure itself is powered by Service Fabric. Service Fabric **IS** Azure and vice versa. And from that factual perspective, a comprehensive example should be pivotal.

**Comment by mikhailshilkov** [comment]
@tedvanderveen I don't think we have any internal expertise in Service Fabric. If you or somebody else wants to contribute an example, we are happy to take it!

**Comment by tedvanderveen** [comment]
@mikhailshilkov let me give it a shot in the coming days. Can you reopen this issue for reference?
