### ISSUE TITLE
Edit the helm chart for azure-ts-aks-helm

### ISSUE THREAD

**Issue by arycloud** [pulumi/examples#207]
Is there a way to edit the helm chart for `azure-ts-aks-helm` because I want to pass my own GitHub repo to build helm chart for.

Help me, please!

**Comment by lblackstone** [comment]
I'm not quite sure I understand your question, but you can configure the program to use any helm chart you like.

https://github.com/pulumi/examples/blob/e3dd441159d74628ac06a06b89de354a804f2301/azure-ts-aks-helm/index.ts#L7-L15

This example is pulling bitnami/apache@1.0.0, but you can choose the repo/chart@version.

**Comment by stack72** [comment]
Hi @lblackstone 

Is this something we need to change or something we can close out?

P.
