### ISSUE TITLE
Missing Plugins: for gcp-ts-gke example

### ISSUE THREAD

**Issue by jkogut** [pulumi/examples#231]
It would be informative++ to have this info in **gcp-ts-gke** example README file:
```
pulumi plugin install resource gcp v0.16.7
pulumi plugin install resource kubernetes v0.13.0
```

[ + ] Pulumi told me about missing gcp resource and how to install it 
[ - ] Pulumi told me about missing kubernetes resource without its version
[ - ] Do not know how to list available plugins with its versions ... so used [this one](https://github.com/pulumi/pulumi-kubernetes/issues/64)
[ ? ] Maybe it would be nice to implement something like this:
```
pulumi plugin ls available
```

**Comment by lukehoban** [comment]
The step that’s missing is actually `npm install`. That will take care of installing the two packages at the versions specified in package.json, as well as downloading the required plugin versions used by each of those packages. 

You should in general not need to manually install plugins.

**Comment by jkogut** [comment]
hmmm, that is very weird ... I was trying to focus on README as much as possible (so, I did that step before ...) that's from my bash history:
``` 
 1734  npm install
 1735  pulumi up
 1736  pulumi plugin install resource gcp v0.16.7
```

**Comment by lukehoban** [comment]
Oh - I thought I saw that the `npm install` step was actually missing from the readme.

If you did run that, did it error?  That step should have installed all the required plugins.  If you happen to still have the output from `npm install` that would be helpful.

**Comment by jkogut** [comment]
> Oh - I thought I saw that the npm install step was actually missing from the readme.

very true, just remembered that step from your awesome **TGIK8s with Joe Beda** video :+1: :ok_hand:  

Maybe the problem was because of the node upgrade I did meanwhile ... Will try to reproduce it.

**Comment by jkogut** [comment]
[SOLVED](https://github.com/pulumi/examples/issues/232)
