### ISSUE TITLE
Travis tests failing frequently

### ISSUE THREAD

**Issue by lukehoban** [pulumi/examples#238]
We’ve seen Travis tests fail several times in the last week, and the build still shows as broken. We need to keep this green, as it’s a key regression test suite. 

Also, the Travis tests appear to now take 1:45 to run, which is likely not safe - given 2h cutoff in Travis. We should understand the long pole here, and find ways to adjust tests to be less than 1h.

**Comment by CyrusNajmabadi** [comment]
We're passing again, and tend to take around 50 minutes per run.  Looking at the failures, i noticed several in an azure test.  I've increased the timeout there in case it's just a case of azure taking a very long time to spin up.

**Comment by CyrusNajmabadi** [comment]
There's a good indication this is just a timeout problem, and that the increased timeouts help:

```
Http Error: Get http://ec2-18-237-40-31.us-west-2.compute.amazonaws.com/notes: dial tcp 18.237.40.31:80: connect: connection refused
  Retry: 13, elapsed wait: 6m20.68149047s, max wait 10m0s
```

This was the last error we got before the ruby-on-rails test finally passed.  So, it looks like our previous timeout of 5min was just a little too aggressive based on how long these thins can take sometimes.

**Comment by CyrusNajmabadi** [comment]
I'm satisfied with our current passing rate here.
