### ISSUE TITLE
Create Service for HTTPS trafic.

### ISSUE THREAD

**Issue by Ilchuk-Mihail** [pulumi/examples#268]
Maybe you have some example for this ? 

Error: Cannot create Service for HTTPS trafic. No ACM certificate ARN configured.

**Comment by lukehoban** [comment]
The error could be a little more explicit - but it's saying you need to set the `pulumi config set cloud-aws: acmCertificateARN` config variable as described in https://pulumi.io/quickstart/cloudfx/index.html#configuration.

In general though, for these use cases where you need to take advantage of more AWS-specific capbabilities, we're generally recommending the `@pulumi/awsx` package, which makes this sort of thing much easier and more flexible.  See https://github.com/pulumi/pulumi-awsx/tree/master/nodejs/awsx/elasticloadbalancingv2 for several examples in this space.

**Comment by Ilchuk-Mihail** [comment]
@lukehoban 
Thanks for response. 
This config variable doesn't help.

There is no option to create url  via https ?
For elastic load balancer  .....elb.amazonaws.com  .

**Comment by lukehoban** [comment]
> This config variable doesn't help.

Can you provide more details?  I know of several users using this config setting today - so I expect there must be something specific in your case that is causing problems?  Could you share an example perhaps?

> There is no option to create url via https ?

This should be possible by setting `containerProtocal: "https"`.  Would love to understand what you are trying that is not working.  https://pulumi.io/reference/pkg/nodejs/@pulumi/cloud/index.html#ContainerPort-protocol

**Comment by Ilchuk-Mihail** [comment]
```
"use strict";
const cloud = require("@pulumi/cloud");

let service = new cloud.Service("d-server", {
    containers: {
        dserver: {
            build: "../", 
            memory: 512,
            ports: [{ port: 80, protocol: "http", targetPort: 3000 }],
        },
    }
});

// export just the hostname property of the container frontend
exports.url = service.defaultEndpoint.apply(e => `http://${e.hostname}`);

```
If I use that command - `pulumi config set cloud-aws: acmCertificateARN`
I get that in Pulumi.dev.yaml :

```
config:
  aws:region: us-east-1
  'cloud-aws:': acmCertificateARN
  cloud-aws:useFargate: "true"
  cloud:provider: aws

```

And if I change ports to -> `  ports: [{ port: 80, protocol: "https", targetPort: 3000 }],` I have the same Error: Cannot create Service for HTTPS trafic. No ACM certificate ARN configured. 

How this config should look like  ` cloud-aws:acmCertificateARN` ? 
Or I need to paste arn for this certificate ` cloud-aws: acmCertificateARN: "there" `  and it only acceptable for custom domain names ? 

I only want my result url to work via https. Default result point is ELB. 
.... .us-east-1.elb.amazonaws.com

How can I do that for this domain ? or is it only possible for custom domains

**Comment by lukehoban** [comment]
Apologies - I had a typo in my previous reply - I meant:

```
pulumi config set cloud-aws:acmCertificateARN myACMCertARNValue
```

where `myACMCertARNValue` is an ACM cert ARN you get from the AWS console or API.
