### ISSUE TITLE
Destroying aws-ts-static-website example stack is tricky

### ISSUE THREAD

**Issue by Blitz2145** [pulumi/examples#269]
When destroying the resources for the example, you first must do a `pulumi refresh` or it seems to fail with
```
  aws:cloudfront:Distribution (cdn):
    error: Plan apply failed: deleting urn:pulumi:dev::web-prototype::aws:cloudfront/distribution:Distribution::cdn: error updating CloudFront Distribution (E344685LBUTE91): PreconditionFailed: The request failed because it didn't meet the preconditions in one or more request-header fields.
    	status code: 412, request id: 11d27cb0-5645-11e9-b5cd-bfecda5ab876
```
After `pulumi refresh` and then `pulumi destroy`:
```
BucketNotEmpty: The bucket you tried to delete is not empty
    	status code: 409, request id: 3206D3B5DBED8A5F, host id: N17erlHahz/G+a1xO8vknKoUM9wd3dw5HRVDt964f6qar+y1E4jDfA85rsf2+RlA6r6gh7yQG3w=
```
Seems like a partially known problem https://github.com/pulumi/pulumi-terraform/issues/57 but its not a great experience, perhaps the README could document the steps needed to destroy in the meantime. Its a great example of pulumi btw.

**Comment by stack72** [comment]
I am going to track the work to fix this in #337
