### ISSUE TITLE
'deploy to pulumi' button isn't working for azure-ts-appservice-devops

### ISSUE THREAD

**Issue by johnstrickermayo** [pulumi/examples#319]
I'm getting the following error:

Could Not Load Template
Could not load template project at https://raw.githubusercontent.com/pulumi/examples/master/azure-ts-appservice-devops/Pulumi.yaml (based on template https://github.com/pulumi/examples/tree/master/azure-ts-appservice-devops).

**Comment by clstokes** [comment]
I see the same error as John. (Screenshot below).

@johnstrickermayo I just tested this via the command line with `pulumi new <url>` and was able to get started with it that way:
```
$ pulumi new https://github.com/pulumi/examples/tree/master/azure-ts-appservice-devops
This command will walk you through creating a new Pulumi project.

Enter a value or leave blank to accept the (default), and press <ENTER>.
Press ^C at any time to quit.

project name: (azure-appservice) 
project description: (Creates a Todo App on Azure App Service with SQL Database and Application Insights and deploys it to Azure DevOps)
Created project 'new-azure-ts-appservice-devops'

stack name: (dev)
Created stack 'dev'

azure:environment: The Azure environment to use (`public`, `usgovernment`, `german`, `china`): (public)
sqlPassword: Azure SQL Server password (complex enough to satisfy Azure policy):
sqlUsername: Azure SQL Server username:
Saved config

Installing dependencies...
...
```

Screenshot from service:
![image](https://user-images.githubusercontent.com/293763/59876153-b0d99c80-9357-11e9-8fbc-52fce61df9ab.png)

**Comment by mikhailshilkov** [comment]
I suppose that's because of the unusual folder structure that I picked for that example. It was tailored for Azure DevOps, not manual deployment.

**Comment by lukehoban** [comment]
FWIW - the issue is that there is no `Pulumi.yaml` in the root of this example where the "Deploy" button is.

We should either:
1. Remove the button from this folder, or
2. Redirect the button to the subfolder (not sure if that really accomplishes the goal of the example, or if it's possible with our deploy button currently).

I suggest we just do (1) for now.

**Comment by johnstrickermayo** [comment]
thanks guys!
