### ISSUE TITLE
Python AWS static web site needs Route53 example

### ISSUE THREAD

**Issue by davedittrich** [pulumi/examples#323]
As I know you are aware, the Python examples are not anywhere near as well documented as the Typescript examples. Unfortunately, I code in Python (no experience with Typescript at all). I am struggling mightily trying to figure out how to replicate the AWS Route53 portion found in this example:

https://github.com/pulumi/examples/blob/4b978f90d0abfac5e3c8086f7c125a5b09972afa/aws-ts-static-website/README.md

Could someone please work out the Route53 equivalent Python code from that example and add it to the `aws-py-webserver` example, or replicate the `aws-ts-static-website` example for Python?

Thanks!

**Comment by leezen** [comment]
https://github.com/pulumi/examples/pull/573
