### ISSUE TITLE
minor documentation (or project name) correction for azure-ts-appservice-devops

### ISSUE THREAD

**Issue by johnstrickermayo** [pulumi/examples#324]
In the pulumi.yaml, the name is specified as `azure-appservice`

while the documentation uses the name of `azure-appservice-devops`:

6. Define SQL Server username:

pulumi config set azure-appservice-devops:sqlUsername <value>

7. Define SQL Server password (make it complex enough to satisfy Azure policy):

pulumi config set --secret azure-appservice-devops:sqlPassword <value>

**Comment by mikhailshilkov** [comment]
@johnstrickermayo Thanks for taking time to report this!

@lukehoban Do I understand correctly that specifying the project name in `pulumi config` is optional? Should we just document the commands as `pulumi config set sqlUsername <value>`?

**Comment by lukehoban** [comment]
> Should we just document the commands as pulumi config set sqlUsername <value>?

Yes - that’s the typical approach.
