### ISSUE TITLE
azure-ts-appservice-docker sporadically hits a runtime error trying to deref a nil pointer

### ISSUE THREAD

**Issue by metral** [pulumi/examples#350]
```
program.go:423: panic testing /home/travis/gopath/src/github.com/pulumi/examples/azure-ts-appservice-docker: runtime error: invalid memory address or nil pointer dereference`
```

Full Travis CI output of a cron run on `pulumi/examples`: https://gist.github.com/metral/65ab2cb93ce6dcd7c24ecccd66cefcaf#file-log-txt-L3346-L3347

https://s3-us-west-2.amazonaws.com/eng.pulumi.com/travis-logs/pulumi/examples/912.1/failed-tests.tar.gz

**Comment by metral** [comment]
cc @stack72

**Comment by stack72** [comment]
@mikhailshilkov I'd love your thoughts here - I can't see what the issue is - I can bring these resources up locally but I get nothing from the endpoints...

**Comment by lukehoban** [comment]
FWIW - I would bet this is a panic in the `ExtraRuntimeValidation` for this particular test.

We should also render stack traces in the recover handler here so that we have a chance of debugging these in the future. 

> I get nothing from the endpoints

What do you mean by this?

**Comment by stack72** [comment]
there is no output coming from the pulumi stack output - it's almost as though the service hasn't deployed correctly but yet I can see it has according to pulumi

I am tracing the panic down but this feels like we have an issue elsewhere in Azure that this is masking

**Comment by stack72** [comment]
So, I just checked back in on this test - it has actually passed it's test run last night - and no changes were made to it. I think this was an issue elsewhere...

**Comment by stack72** [comment]
So this has been fixed - basically, we hit a panic when trying to defer on resp.body.close when we didn't have a response from the service

This is not guarded against

**Comment by metral** [comment]
This error resurfaced in the same test.

Logs: https://gist.github.com/eba740922581fcb55dbebd3d2aa140ac

**Comment by metral** [comment]
```
    --- FAIL: TestExamples/azure-ts-appservice-docker (1530.75s)
        examples_test.go:833: 
            	Error Trace:	examples_test.go:833
            	            				examples_test.go:775
            	            				examples_test.go:387
            	            				program.go:1022
            	            				program.go:768
            	            				program.go:651
            	            				program.go:445
            	            				examples_test.go:769
            	Error:      	Expected value not to be nil.
            	Test:       	TestExamples/azure-ts-appservice-docker
            	Messages:   	resp was nil
        program.go:423: panic testing /home/travis/gopath/src/github.com/pulumi/examples/azure-ts-appservice-docker: runtime error: invalid memory address or nil pointer dereference
```

**Comment by stack72** [comment]
@metral so @mikhailshilkov made some changes to the test in #365 to make it more robust
