### ISSUE TITLE
Failures in some GKE examples

### ISSUE THREAD

**Issue by ellismg** [pulumi/examples#352]
Across the last few CI runs, we've seen an error in the initial update of our GKE examples, where the service never is allocated an IP Address:

```
[ com/pulumi/examples/gcp-py-gke ]     error: Plan apply failed: 2 errors occurred:
[ com/pulumi/examples/gcp-py-gke ]     	* Timeout occurred for 'ingress-kcl7grr3'
[ com/pulumi/examples/gcp-py-gke ]     	* Service was not allocated an IP address; does your cloud provider support this?
```

We've seen this for both the `gcp-py-gke` example and `gcp-ts-gke-hello-world` (the actual infrastructure these programs describe are very similar.

Looks like it has failed in at least three builds:

https://travis-ci.com/pulumi/examples/builds/121028457
https://travis-ci.com/pulumi/examples/builds/121194660
https://travis-ci.com/pulumi/examples/builds/121212651

I am a little concerned that something so simple seems to continue to fail for us.

**Comment by ellismg** [comment]
Note that we did get this mail from Google recently:

> Hello Google Kubernetes Engine Customer,
>
>We’re writing to let you know that beginning on July 30, 2019, new clusters created using gcloud version 256.0.0 will, by default, be routes-based instead of VPC-native.
>
>Despite this gcloud change in the default mode of GKE cluster creation, we still recommend that users opt-in to create GKE clusters in VPC-native mode; we are working on making VPC native the configuration default in the future.
>
>What do I need to know?
>Routes-based clusters use a single CIDR range for both Pod IP addresses and Service IP addresses. Whereas VPC-native clusters use Alias IP secondary ranges for the IP address ranges of the cluster. One range is reserved for Pod IP addresses, and another is reserved for Service IP addresses.
>
>Currently, the GKE Cluster creation API creates clusters by default in Routes-based mode, however, gcloud and Cloud Console created clusters are by default created in VPC-native mode. Beginning on July 30, 2019, with gcloud version 256.0.0, by default, clusters created through gcloud will also be Routes-based. This change only impacts newly created clusters; there will be no changes to existing clusters. gcloud versions 251.0.0 through 255.0.0 and Cloud Console created clusters will be in VPC-native mode by default.
>
>What do I need to do?
When creating new clusters using gcloud version 256.0.0, you will need to use the following gcloud command to create VPC-native clusters:
>
>gcloud container clusters create NAME --enable-ip-alias
>
>Using the flag --no-enable-ip-alias will create a routes-based cluster:
>
>gcloud container clusters create NAME --no-enable-ip-alias
>
>If you have any questions or require assistance, please reply to this email to contact Google Cloud Support.
>
>Thank you for being a valued Kubernetes Engine customer.

I suspect this is happenstance, since I think we should already be using the API instead of gcloud directly, but it could be a reason as to why this is happening.

**Comment by lblackstone** [comment]
I was unable to reproduce the `gcp-ts-gke-hello-world` failure locally; it ran fine for me.

Given the repeated failures in CI, I suspect that the LoadBalancers may be taking longer than expected to provision occasionally. I'm considering overriding the timeout for that Service to be a little longer.

**Comment by ellismg** [comment]
It is possible that we were hitting limits in our GCP project, the one we specifically use for CI.  I had seen other tests failed that tried to allocate load balancers directly (because they would create health checks and we had hit limits there) so it's possible some similar limit was being hit and so the external IP was never assigned.  I have cleaned up a bunch of the leaked stuff in our testing account and we'll see if this continues to be a problem in tonight's run.

**Comment by ellismg** [comment]
It appears that that was likely the issue, as these tests are no longer failing.
