### ISSUE TITLE
Do a pass over examples for consistency

### ISSUE THREAD

**Issue by joeduffy** [pulumi/examples#371]
Now that we're rendering examples as tutorials in the docs website, we should do a pass over the examples for consistency. We're leaning towards leveraging Digital Ocean's guidelines -- https://www.digitalocean.com/community/tutorials/digitalocean-s-technical-writing-guidelines -- which will force us to ensure good titles, clean up the H2/H3s, and be better about listing prerequisites. As we make progress on this, we should regenerate the docs tutorials.

Taken from https://github.com/pulumi/docs/issues/1577#issuecomment-524687612:

- [x] Check in tutorial guidelines (similar to [DO's](https://www.digitalocean.com/community/tutorials/digitalocean-s-technical-writing-guidelines))
- [x] Tidy up the example titles/READMEs to conform to them and ensure they still work (with consistent casing)
- [ ] Reconcile duplication between existing tutorials and examples
- [x] Figure out what to do with tutorials that don't already exist as examples
- [x] Link to a decent example tutorial from the template file

**Comment by mikhailshilkov** [comment]
Asked a related question in the docs repo: https://github.com/pulumi/docs/issues/1577#issuecomment-526077425

**Comment by bermudezmt** [comment]
Let's continue the discussion here:

> @mikhailshilkov This is definitely the major difference that @bermudezmt and I have been discussing what to do about. I think we want the examples READMEs to be written in a more tutorial style, so that they read better in both places. It doesn't hurt to have more detail on GitHub too. But the challenge is that this is going to be a fair bit more effort and there is a lot of debt to pay down since none of the examples are written this way.

> @bermudezmt What are you thinking about this these days?

I do think we should create future examples with the idea that it's going to be transformed into a tutorial for the docs site. And I really like Digital Ocean's guidelines. 

I wonder if we can actually have a note for existing examples that have been turned into tutorials. It will be similar to our "derived" note from our package reference pages (https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/dnsimple/). This way we standardize for future examples and tutorials, but do not burden ourselves with redoing _all_ of the READMEs for the existing ones.

It might be good to add the tutorials that don't exist as examples to this repo.

**Comment by mikhailshilkov** [comment]
I suspect we don't need *every* example to be a tutorial. For instance, [Azure doc page](https://www.pulumi.com/docs/tutorials/azure/) currently has four featured tutorials, so we could write four step-by-step guides and leave other examples as-is. Which brings us back to the old situation when we have examples and manually written tutorials...

**Comment by bermudezmt** [comment]
@justinvp Not sure if you wanted to leave this issue open or track the remaining work to do: I'll link to the EC2 Web Server Tutorial in the example template file. The idea is that the featured tutorials will continue to be multi-language as I've started doing at http://content-bucket-ce8f9d2.s3-website-us-east-1.amazonaws.com/docs/tutorials/aws/ec2-webserver/.

So it will probably make more sense to update the tool so it would skip the autogeneration of the featured tutorials (https://github.com/pulumi/examples/tree/master/aws-js-webserver and https://github.com/pulumi/examples/tree/master/aws-py-webserver for example).

**Comment by lukehoban** [comment]
@chrsmith Did https://github.com/pulumi/docs/pull/1786 close this out?  Or if not, what is remaining here - and is it concrete enough or should we open more specific issues?

**Comment by chrsmith** [comment]
@lukehoban From my interpretation of the thread here, and #391, we are probably in good enough shape to close this issue out for the current milestone. Though I'll spend some amount of time later today editing some of the existing `README.md` files to reflect the newer, suggested style. So that more things are consistent than not.
