### ISSUE TITLE
Environments/stages as separate projects?

### ISSUE THREAD

**Issue by atraver** [pulumi/examples#406]
I spoke with @stack72 about this in Slack and he suggested opening an issue about it here.

I use Terraform to manage my infrastructure, and have 3 AWS accounts: dev, staging, and prod. Each environment/stage is represented by a different AWS account to segregate my resources and control access. I'm trying to evaluate Pulumi as a replacement, but am finding it hard to map my existing Terraform structure to Pulumi concepts.

The Terraform directory/config structure for my infrastructure looks something like this:
```
dev/
  apps/
    api-content/main.tf
    website/main.tf
  s3/main.tf
  vpc/main.tf
modules/
  elastic-beanstalk/main.tf
staging/
  apps/
    api-content/main.tf
    website/main.tf
  vpc/main.tf
prod/
  ...
```
There are commonalities between each account, which is why I have the shared module for creating Elastic Beanstalk environments. However, the `dev` account's `api-content` application might have 3 Elastic Beanstalk environments -- since I use it for testing new functionality -- whereas the `staging` and `prod` accounts might only have 1. As such, it seems like creating Pulumi projects called `api-content` and `website` and 3 stacks (dev, staging, and prod) for each project might not be the best case, since my Pulumi source file would have to have at least a few if/else cases to conditionally describe these test Elastic Beanstalk environments, among other things.

What I'd like to see -- or maybe hear of a better approach -- would be how to describe my infrastructure using Pulumi such that I can have both shared infrastructure (e.g., a `common` project) that contains component resources to create Elastic Beanstalk environments, etc., as well as some way to manage each account without resorting to a bunch of conditional logic in my code.

I realize this would be easier if my infrastructure was a lot more similar between my accounts, such that the only differences were easy to describe in a Pulumi config (e.g., 1 EC2 instance per Elastic Beanstalk environment in dev vs. 4 in prod) but having a number of  different resources in each account makes me wonder if using stacks for my accounts is the way to go, or if I should do something else like this:

```
common/
  elastic-beanstalk.ts
  Pulumi.yaml
dev/
  api-content.ts
  index.ts
  Pulumi.yaml
  s3.ts
  vpc.ts
staging/
  api-content.ts
  index.ts
  Pulumi.yaml
  vpc.ts
...
```
That way, each account would be a Pulumi project with a single stack, and could be managed separately, while still benefiting from common components where it makes sense. 

One potential downside I can see to this approach is that currently, if I want to make a change to my `dev/apps/api-content/main.tf` config, I can do it without running `terraform apply` against the entirety of my `dev` account, since each application/service is a separate config. But if the entire `dev` account was one Pulumi project, it would have to query all of my account's resources to determine diffs, which could take quite a while as I add more resources to my accounts.

Any help would be appreciated.

**Comment by pgavlin** [comment]
cc @lukehoban

**Comment by spender0** [comment]
+

**Comment by leezen** [comment]
I think the approach outlined in the original question seems like a potentially reasonable approach. At the end of the day, the whole concept of "stacks" and "projects" are intentionally flexible to allow various organization methods [1].

One addendum to the above split of dev/prod into separate projects would be to further split into sub-projects where independent components could be managed. I think that pretty much gets you to the same structure as in the TF setup originally described:

```
dev/
  apps/
    api-content/index.ts
    website/index.ts
  s3/index.ts
  vpc/index.ts
modules/
  elastic-beanstalk/index.ts
staging/
  apps/
    api-content/index.ts
    website/main.ts
  vpc/main.ts
prod/
...
```

[1] See also: https://www.pulumi.com/docs/intro/concepts/organizing-stacks-projects/

**Comment by scottslowe** [comment]
@atraver @spender0 Do you still have outstanding questions that we can help address?

**Comment by atraver** [comment]
Not from me, nope.
