### ISSUE TITLE
Add more Go language examples

### ISSUE THREAD

**Issue by stack72** [pulumi/examples#442]
We want to add more examples that show off the Go support we have

**Comment by EvanBoyle** [comment]
These should run in CI (at least some subset).

**Comment by ekrengel** [comment]
@EvanBoyle Please add some examples that you would like @tasiah to work on. We will start her off with this to get up to speed with the Go programming model.

**Comment by EvanBoyle** [comment]
Here are some ideas for things that we could convert to go:

1. [aws-cs-lambda](https://github.com/pulumi/examples/tree/master/aws-cs-lambda)
2. [gcp-cs-function](https://github.com/pulumi/examples/tree/master/gcp-cs-functions)
3. [gcp-ts-gke](https://github.com/pulumi/examples/blob/master/gcp-ts-gke/index.ts) This is dependant on the kubernetes go work https://github.com/pulumi/pulumi-kubernetes/issues/70
4. [azure-cs-aks](https://github.com/pulumi/examples/tree/master/azure-cs-aks)
