### ISSUE TITLE
azure-cs-aks: "Error creating Managed Kubernetes Cluster"

### ISSUE THREAD

**Issue by danvanderboom** [pulumi/examples#480]
I attempted to deploy the azure-cs-aks example and got the following error:

error: update failed
 
aksCluster (azure:containerservice:KubernetesCluster)
error: Error creating Managed Kubernetes Cluster "aksclusterfacdf82c" (Resource Group "aks-rgcd236d56"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ServicePrincipalNotFound" Message="Service principal clientID: 1ea93343-e615-49b7-88f5-0fa1875a9a59 not found in Active Directory tenant 6c9ec2e0-0682-44bb-b2c3-2c5ca5ad1031, Please see https://aka.ms/aks-sp-help for more details."

**Comment by lukehoban** [comment]
Curious - if you do another `pulumi up` - does it succeed? I believe this may be due to eventual consistency issues between AAD and AKS.

**Comment by danvanderboom** [comment]
I had already destroyed the resources by the time I got this message. But when I did a fresh "pulumi up" again, it worked.

**Comment by mikhailshilkov** [comment]
Yeah, we have this note in some readmes:

> Note: Due to an issue in the Azure Terraform Provider (https://github.com/terraform-providers/terraform-provider-azurerm/issues/1635) the creation of an Azure Service Principal, which is needed to create the Kubernetes cluster (see cluster.ts), is delayed and may not be available when the cluster is created. If you get a Service Principal not found error, as a work around, you should be able to run pulumi up again, at which time the Service Principal should have been created.

Despite the mentioned issue is closed, it looks like the issue still pops up from time to time.

**Comment by lukehoban** [comment]
@mikhailshilkov Should we add a note to this README as well?  Or is there any other action we can take?

Else we should probably close this out.

**Comment by mikhailshilkov** [comment]
The proper links to track here:
- Terraform [issue](https://github.com/terraform-providers/terraform-provider-azuread/issues/156)
- Azure AKS [issue](https://github.com/Azure/AKS/issues/1206)
- Azure AKS [faq](https://docs.microsoft.com/en-us/azure/aks/troubleshooting#im-receiving-errors-that-my-service-principal-was-not-found-when-i-try-to-create-a-new-cluster-without-passing-in-an-existing-one)

I updated the README's in #481

**Comment by mikhailshilkov** [comment]
Closing this for now with the workarounds and issues to watch above
