### ISSUE TITLE
Travis builds are failing

### ISSUE THREAD

**Issue by lukehoban** [pulumi/examples#494]
We're seeing several consistent failures that appear to be real issue - a combination of TypeScript breaks, Azure breaks, and something weird with GCP resources.  These are reproducing over all build combinations for the last week (with the last green CRON run 27 days ago).

**Comment by mikhailshilkov** [comment]
An Azure issue is tracked here https://github.com/pulumi/pulumi/issues/3621

**Comment by stack72** [comment]
Closed via #495
