### ISSUE TITLE
pulumi up: Authenticate user against Active Directory?

### ISSUE THREAD

**Issue by scheung38** [pulumi/examples#496]
Win 10: pulumi up

Last executed rule : Authenticate user against Active Directory

is this because I am login as user, but it is not associated with AD? If so how to resolve this so I can perform a successful pulumi up ? or I need to specifically ask company IT Helpdesk to whitelist it?

**Comment by leezen** [comment]
Could you please provide more details about the issue you're seeing? Where is that output coming from? Are you trying to run a specific example? What is your environment setup?

**Comment by stack72** [comment]
I am going to close this out - we have not heard back from the OP on this and a month has passed. Please feel free to reopen if there are more details on how to recreate this
