### ISSUE TITLE
aws-ts-eks - Fargate Support

### ISSUE THREAD

**Issue by nsisodiya** [pulumi/examples#506]
Recently AWS introduced Fargate support for EKS. It means, we can run containers on fargate instead of worker node. Please correct if my understanding is wrong.
May you please provide sample example to create EKS with Fargate support.

When I check source code - https://github.com/pulumi/examples/blob/master/aws-ts-eks/index.ts , I don't see security group, iam roles etc.

**Comment by lukehoban** [comment]
There is support for Fargate + EKS in the `@pulumi/eks` package - and notes on how to use that here: https://www.pulumi.com/blog/aws-eks-managed-nodes-fargate/.
