### ISSUE TITLE
Example needed: awk-eks-fargate-nodejs-app

### ISSUE THREAD

**Issue by nsisodiya** [pulumi/examples#507]
Pulumi is great, In just one day, I am able to deploy EKS cluster.
It will be really great if somebody help me in making this demo.

Requirement
=========
1. deploy below nodejs code using "ECR" and AWS EKS
2. use helm chart to deploy docker image
3. final url should be - https://api.mydomain.com/hello-service
4. assume cicd pipeline working perfectly and it push image to ECR. 

This is the js file. taken from https://medium.com/@sssanjaya/a-simple-docker-setup-for-simple-hello-world-nodejs-application-bcf79bb608a0

```js
//now it load express module with `require` directive
var express = require('express')
var app = express()
//Define request response in root URL (/) and response with text Hello World!
app.get('/', function (req, res) {
  res.send('Hello World!')
})
//Launch listening server on port 8080 and consoles the log.
app.listen(8080, function () {
  console.log('app listening on port 8080!')
})
```
and this is the Docker file.

```sh
## it uses node js image alpine version from image registries.
FROM node:8.16.1-alpine
## it sets directory in the container to /app to store files and launch our app.
WORKDIR /app
## it copies the app to /app directory with dependencies.
COPY package.json /app
RUN npm install
COPY . /app
## it commands to run our app which is index.js.
CMD node index.js
##  it exposes the port where our app is running that is port 8080.
EXPOSE 8080
```

**Comment by leezen** [comment]
We have some examples for deploying helm charts, e.g. https://github.com/pulumi/examples/tree/master/aws-ts-eks and https://github.com/pulumi/examples/tree/master/kubernetes-ts-helm-wordpress

For building your own helm chart, I'd suggest checking out some existing resources on that, e.g. https://github.com/helm/helm/tree/master/cmd/helm/testdata/testcharts/alpine

In terms of EKS and ECR, I'd suggest taking a look at this blog post: https://www.pulumi.com/blog/building-and-publishing-docker-images-to-a-private-amazon-ecr-repository/
