### ISSUE TITLE
missing .classpath file for azure-ts-appservice-springboot

### ISSUE THREAD

**Issue by whitwofl1** [pulumi/examples#562]
.classpath file is missing from azure-ts-appservice-springboot 

PS C:\project\azure-ts-appservice-springboot\infrastructure> pulumi up
Previewing update (dev):

     Type                   Name                      Plan     Info
     pulumi:pulumi:Stack    jenkins-tutorial-dev
     └─ docker:image:Image  spring-boot-greeting-app           2 errors

Diagnostics:
  docker:image:Image (spring-boot-greeting-app):
    error: Error: ' docker build ../ -t myacref5a887b.azurecr.io/spring-boot-greeting-app:v1.0.0' failed with exit code 1
    Sending build context to Docker daemon  138.1MB
    Step 1/10 : FROM gradle:5.6-jdk11 as build
     ---> ae10e1a51333
    Step 2/10 : WORKDIR /app
     ---> Using cache
     ---> 4e6f91b86a22
    Step 3/10 : COPY ./src ./src
     ---> Using cache
     ---> 715489b40a3b
    Step 4/10 : COPY build.gradle .
     ---> Using cache
     ---> 78bd54453ede
    Step 5/10 : COPY .classpath .

        at C:\project\azure-ts-appservice-springboot\infrastructure\node_modules\@pulumi\docker.ts:589:15
        at Generator.next (<anonymous>)
        at fulfilled (C:\project\azure-ts-appservice-springboot\infrastructure\node_modules\@pulumi\docker\docker.js:18:58)
        at processTicksAndRejections (internal/process/task_queues.js:94:5)

    error: COPY failed: stat /var/lib/docker/tmp/docker-builder117625329/.classpath: no such file or directory

**Comment by leezen** [comment]
Thanks for letting us know -- we'll look into it.

**Comment by mikhailshilkov** [comment]
@praneetloke was it you who put this example together? Any idea what's broken?

**Comment by praneetloke** [comment]
@mikhailshilkov yes. I am looking into it.

**Comment by praneetloke** [comment]
@whitwofl1 it turns out that the `.classpath` was ignored because of a root `.gitignore` and wasn't checked in. However, I just tested by removing the `COPY classpath .` line from the `Dockerfile` and it works fine with out it. I'll raise a PR to remove it, but could you please try to change the `Dockerfile` and let me know how it goes for you?

Also, curious which IDE you are using? Typically, IDEs like IntelliJ or Eclipse will recreate the `.classpath` file upon project import.

**Comment by whitwofl1** [comment]
@praneetloke I did wind up downloading eclipse that day and it did create the .classpath for me, However I did not think this example was dependant on having a IDE ( normally I just use visual studio code) .

**Comment by praneetloke** [comment]
> However I did not think this example was dependant on having a IDE

You are right. It definitely should not be IDE-dependent. I was only curious which IDE you were using. I will raise the PR to remove copying the `.classpath` from the `Dockerfile`. I don't remember now why it was even added in the `Dockerfile`, maybe a Spring Boot starter that had it originally?
