### ISSUE TITLE
Add `dep ensure` as a step in the Go READMEs

### ISSUE THREAD

**Issue by tasiah** [pulumi/examples#567]
See discussion [here](https://github.com/pulumi/examples/pull/563#issuecomment-587224725). `dep ensure` is a necessary step to ensure our go examples work from a clean state and we should reflect that in our documentation. `dep ensure` currently isn't mentioned in any of our Golang examples.

cc @stack72 @lukehoban

**Comment by EvanBoyle** [comment]
Can we close this in favor of https://github.com/pulumi/pulumi/issues/3817?

**Comment by lukehoban** [comment]
Works for me. So we have a plan for https://github.com/pulumi/pulumi/issues/3817 yet?  Last I heard it was going to be “hard” (something about multi-gomod repos not being very well supported by current tools).

**Comment by EvanBoyle** [comment]
Ah, I was not aware. Let's leave this open and I can close it if I find a
solution for modules.
