### ISSUE TITLE
Add Kubernetes + JavaScript example

### ISSUE THREAD

**Issue by zchase** [pulumi/examples#590]
We currently do not have any examples for Kubernetes + JavaScript. We are working on a nurturing email that has a table with links and right now we cannot link to anything.

Current examples: https://github.com/pulumi/examples#kubernetes

**Comment by lukehoban** [comment]
I suspect we may not want to do this one.  In general, I think we are okay having TS examples instead of JS examples for most things.  From a user code perspective they are nearly identical.

**Comment by zchase** [comment]
Following up on @lukehoban comment above. We are going to eliminate the JS row in the email and just have the TS examples. Closing
