### ISSUE TITLE
Travis nightlies failing due to HDInsight

### ISSUE THREAD

**Issue by lukehoban** [pulumi/examples#595]
We're seeing failures across all legs of our nightly tests due to:

```
[ mples/azure-ts-hdinsight-spark ]     error: Error creating HDInsight Spark Cluster "myspark7d82811b" (Resource Group "spark-rg7454ca33"): hdinsight.ClustersClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="User SubscriptionId '0282681f-7a9e-424b-80b2-96babd57a8a1' does not have cores left to create resource 'myspark7d82811b'. Required: 20, Available: 19."
```

It's unclear what if anything we changed in our subscription that started causing this.  We should consider one of:
1. Requesting quota increase
2. Reducing the CPU needs of this example/test
3. Discontinue running this particular example in nightly tests of `pulumi/examples`

**Comment by mikhailshilkov** [comment]
Fixed in master by skipping the tests. Azure support still busy deleting our old HDInsights cluster.
