### ISSUE TITLE
C# Example for Azure Function?

### ISSUE THREAD

**Issue by StefH** [pulumi/examples#616]
Can you please make a C# example for creating and deploying an Azure Function?

**Comment by mikhailshilkov** [comment]
Hi @StefH have you looked at. https://github.com/pulumi/examples/tree/master/azure-cs-functions-raw ?

**Comment by StefH** [comment]
Ah. That's new?

Thanks for the link. I will look at that example.

Do you know if this also works for Functions V3 on a Linux App Plan?

**Comment by mikhailshilkov** [comment]
I think it exists since November last year. It's already using V3. For Linux, you need to change the plan to have `Reserved = true` property.

**Comment by StefH** [comment]
https://github.com/pulumi/examples/pull/619

**Comment by mikhailshilkov** [comment]
Resolved in #664
