### ISSUE TITLE
Update Google Cloud Functions example to grant public access

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/examples#640]
Google Cloud Functions have changed to be private by default. Our examples should show how to make them publicly callable with something like

```ts
// Open the function to public unrestricted access
const iam = new gcp.cloudfunctions.FunctionIamMember(`${name}-iam`, {
    cloudFunction: func.name,
    region: func.region,
    role: "roles/cloudfunctions.invoker",
    member: "allUsers",
});
```

**Comment by EvanBoyle** [comment]
@mikhailshilkov does the above snippet work? I believe we need to include an Endpoint to enable this: https://cloud.google.com/endpoints/docs/openapi/get-started-cloud-functions

**Comment by mikhailshilkov** [comment]
@EvanBoyle yes it works, I use it in my small application. Endpoints are not required for Cloud Functions (as opposed to AWS Lambda).
