### ISSUE TITLE
Python helm example

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/examples#671]
We don't currently have an example of installing a helm chart in Kubernetes - this has come up in the community slack. Let's write one!

**Comment by scottslowe** [comment]
I think the recent addition of a Helm chart template in Python addresses this (see https://github.com/pulumi/templates/pull/439, now merged), so I'm going to go ahead and close this issue. Please reopen the issue if you feel that additional action or discussion is needed. Thanks!
