### ISSUE TITLE
AWS Serverless URL

### ISSUE THREAD

**Issue by Tushar5292** [pulumi/examples#687]
How to generate AWS Serverlss URL?
I generated the project in Aws lambda project with tests (.net core).
What I have to do?

**Comment by leezen** [comment]
I'm not really sure what you mean by "serverless URL" -- could you please be more specific? Are you talking about the invoke URL?

**Comment by stack72** [comment]
Hi @Tushar5292 

I am going to close this issue out - if you can provide us with some more information so we can help, then we can reopen this - I am really hoping that you were able to resolve this issue

Thanks

Paul
