### ISSUE TITLE
AWS lambda function with dynamo db

### ISSUE THREAD

**Issue by Tushar5292** [pulumi/examples#690]
Hi @pulumi-bot 

**I am using below lambda function in C#.After API deployment its showing me error internal server error.**Please help me out in this.

**request :
{
"Id":"Test02@xyz.com",
"Password":"Test02@xyz"
}**

 public async Task<APIGatewayProxyResponse> fn_GetUserRegistrationLogin(SSUsers user,ILambdaContext context)
        {
            var dynamoDbClient = new AmazonDynamoDBClient(
            new BasicAWSCredentials(_accessKey, _secretKey),
            new AmazonDynamoDBConfig
            {
                ServiceURL = "https://dynamodb.us-east-2.amazonaws.com",
                RegionEndpoint = RegionEndpoint.USEast2
            });

            // Get 2 levels of query hierarchy items

            Dictionary<string, AttributeValue> item = (await dynamoDbClient.GetItemAsync(new GetItemRequest
            {
                TableName = "Registration",
                ConsistentRead = true,
                Key = new Dictionary<string, AttributeValue>
                {
                    { "Id", new AttributeValue{ S = user.Id } },
                }
            })).Item;
            context.Logger.Log(user.Id);
            context.Logger.Log(user.Password);
            var call = item.Values;
            context.Logger.Log(JsonConvert.SerializeObject(call, Formatting.Indented));
            if (call != null)
            {
                var response = new APIGatewayProxyResponse
                {
                    StatusCode = (int)HttpStatusCode.OK,
                    Body = JsonConvert.SerializeObject(call, Formatting.Indented),
                    Headers = new Dictionary<string, string> { { "Content-Type", "application/json" } }
                };

                return response;
            }
            else
                {
                var response = new APIGatewayProxyResponse
                {
                    StatusCode = (int)HttpStatusCode.BadRequest,
                    Body = string.Empty,
                    Headers = new Dictionary<string, string> { { "Content-Type", "application/json" } }
                };

                return response;
            }
        }

**Comment by leezen** [comment]
Given this is an issue with the function itself and not Pulumi, I'm going to close this issue. I'd suggest adding more logging and checking your Cloudwatch Logs to see what's going on.
