### ISSUE TITLE
Stack Reference in Open Source 

### ISSUE THREAD

**Issue by JordanSimba** [pulumi/examples#752]
Hey, I didn't really know where to ask this question.

But in reading the docs, I can't quite understand whether stack reference is available for Open Source edition users.
If `Stack A` tries to refer to `Stack B` which uses a different `passphrase` to encrypt its values, or a `Project A -> Stack A` tries to refer to `Project B -> Stack B`, how would the current stacks context with some `PULUMI_CONFIG_PASSPHRASE=passphrase1` env var know how to decrypt some secret or output value from the other stack?

**Comment by leezen** [comment]
StackReference is available for open source users.

However, the ability to use different secrets providers across stacks isn't possible today given the way secrets providers work and is tracked in https://github.com/pulumi/pulumi/issues/4665

**Comment by JordanSimba** [comment]
Thank you for the response.
Quick follow up:
Do both stacks have to use the same passphrase?
(In Open source of course)

**Comment by leezen** [comment]
Yes -- if you want the StackReference to work, they need to use the same secrets provider. Note that in the open source, you can also use other secrets provider that aren't just the passphrase: https://www.pulumi.com/docs/intro/concepts/config/#available-encryption-providers

**Comment by JordanSimba** [comment]
But using the same secrets provider doesn't necessarily mean using the same secret right? Or am I misunderstanding?

Ah, yeah I keep saying passphrase, but it's just what I've chosen as I'm exploring the tool!
