### ISSUE TITLE
azure-cs-appservice does not include App Insights

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/examples#753]
The title of the example, azure-cs-appservice, says that it includes App Insights is the example

> Azure App Service with SQL Database and Application Insights

But there is no mention of App Insights [in the stack](https://github.com/pulumi/examples/blob/master/azure-cs-appservice/AppServiceStack.cs).

**Comment by lukehoban** [comment]
The copies of this example in TypeScript and Python do include Application Insights, but it appears that piece is missing from the C# and F# versions.  We should add it and keep these examples consistent across languages.  PRs welcome! :smile:

**Comment by kane-armstrong** [comment]
This should be resolved now, see https://github.com/pulumi/examples/pull/756

**Comment by stack72** [comment]
Closed via #756
