### ISSUE TITLE
App Insights is not fully set up in azure-ts-appservice

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/examples#754]
When the "azure-ts-appservice" example is deployed, App Insights is not fully set up. This is easily seen by accessing the web site (multiple times) and observing that no metrics appear in AppInsights (even after waiting).

If I go to the App Insights tab of the App Service, I can see that App Insights is linked but not enabled.

![image](https://user-images.githubusercontent.com/1784452/89320139-b6bb3b80-d646-11ea-8f52-e7084ab22bed.png)

Sure enough, if I click "Turn on Application Insights", then I can start receiving metrics in App Insights.

How does the stack need to change so that App Insights is automatically enabled?

**Comment by lukehoban** [comment]
@mikhailshilkov Any idea why this might be?

**Comment by mikhailshilkov** [comment]
Looks like something has changed on the Azure side. I added the settings in #755 that the portal adds.
