### ISSUE TITLE
Provide example of using Pulumi to deploy NextJS app on AWS

### ISSUE THREAD

**Issue by thesobercoder** [pulumi/examples#779]
Please provide an example of how to use Pulumi to deploy NextJS to AWS replicating how deployments work on Vercel infrastructure with edge network.

I'm looking for an example which replicates the same behavior as this [component](https://github.com/serverless-nextjs/serverless-next.js) does for `serverless`.

**Comment by vha14** [comment]
I'm giving this a crack, starting with https://github.com/dealmore/terraform-aws-next-js

**Comment by tlinhart** [comment]
@thesobercoder According to [this issue](https://github.com/serverless-nextjs/serverless-next.js/issues/777), there's a chance that v2 will come closer to what you (and me as well) desire.

**Comment by gunar** [comment]
A basic example—onto which we'd build later on—might be:

- Serving static content from CloudFront
- Deploying all api routes as a single Lambda

In theory, `next build` provides all things necessary for this to work.

**Comment by blackgirlbytes** [comment]
for anyone struggling to find the answer to this like I was..I attempted to upload this to an S3 bucket, but struggled due to lack of information. 

What worked for me: 
- I ran `npm build && npm export` which generated the static HTML files for me.
- Then I ran aws s3 sync ../{folder path}/ s3://$(pulumi stack output bucketName) --acl public-read

**Comment by expelledboy** [comment]
I can not find (and trust I have looked) any working example with pulumi. However, I have [found a template](https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/serverless-components/nextjs-cdk-construct/src/index.ts) to start from to begin the process. Scary stuff...

**Comment by T04435** [comment]
Any updates on this, using Pulumi not any other infra as code provider?

Thanks.

**Comment by AutomationD** [comment]
How critical is the advantage of Edge-line deployment vs EC2/ECS + Cloudfront / Cloudflare?

**Comment by lukehoban** [comment]
The PR at https://github.com/pulumi/examples/pull/1475 includes an example of a component that deploys the infrastructure needed to deploy a high-performance Next.js site on AWS using Pulumi.  This leverages [OpenNext](https://open-next.js.org/) which providers a more robust way to package Next.js builds for AWS (and AWS serverless specifically).

**Comment by AutomationD** [comment]
Thanks @lukehoban , looks good!

I'm curious, what are the main benefits of OpenNext deployment vs a container behind a CDN and how important are they for the average user?
