### ISSUE TITLE
How would I create a rolling update on a managed instance group for gcp

### ISSUE THREAD

**Issue by giuseppecrj** [pulumi/examples#780]
So far I've been very impressed and delighted to be using pulumi to model up my infra. I'm stuck in one part

Is there a way to create a [rolling update](https://cloud.google.com/compute/docs/instance-groups/rolling-out-updates-to-managed-instance-groups) for a `gcp.compute.InstanceGroupManager`? or what is the best practice in order to trigger these events.

**Comment by leezen** [comment]
There are probably two primary ways you might do something like this:
1. Call the rolling update API on every deployment as part of an `apply` on the `InstanceGroupManager` outputs. This would work if the API call is idempotent. I'm not super familiar with this API, so I'm not sure if this requesting a rolling update with the same version kicks off any restarts.
2. Create a dynamic provider that manages calling the API for you whenever the template changes and the rolling update needs to be invoked (https://www.pulumi.com/docs/intro/concepts/programming-model/#dynamicproviders)

**Comment by giuseppecrj** [comment]
Yep, this seems to be the path. Is there a way to fetch authentication params that pulumi uses in order to make api calls? 

```
message: 'Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.',
```

**Comment by leezen** [comment]
You can access the provider configuration via `gcp.config` -- https://www.pulumi.com/docs/intro/cloud-providers/gcp/setup/ might be a helpful reference in terms of what Pulumi is using.

**Comment by giuseppecrj** [comment]
Great, thanks.
