### ISSUE TITLE
[Examples] Example packages are out of date

### ISSUE THREAD

**Issue by joeduffy** [pulumi/examples#79]
For instance, in `aws-js-webserver`:

```
{
    "name": "webserver",
    "version": "0.1.0",
    "main": "index.js",
    "dependencies": {
        "@pulumi/pulumi": "^0.12.0",
        "@pulumi/aws": "^0.12.0"
    }
}
```

We should bump everything so folks are on the latest providers.

I noticed this because misconfigured AWS creds gave me the old, terrible error message.

**Comment by ellismg** [comment]
Fixed with #86
