### ISSUE TITLE
azure-ts-aks-mean -- unable to pull helm charts from any repo

### ISSUE THREAD

**Issue by dangersorus** [pulumi/examples#815]
pulumi up
Previewing update (azure-mean)

View Live: https://app.pulumi.com/dangersorus/azure-mean/azure-mean/previews/68190427-0630-4378-a111-286b47970cae

     Type                                         Name                   Plan       Info
 +   pulumi:pulumi:Stack                          azure-mean-azure-mean  create     1 error; 4 messages
 +   ├─ azuread:index:Application                 aks                    create
 +   ├─ azuread:index:ServicePrincipal            aksSp                  create
 +   ├─ azure:core:ResourceGroup                  aks                    create
 +   ├─ azuread:index:ServicePrincipalPassword    aksSpPassword          create
 +   ├─ azure:cosmosdb:Account                    cosmosDb               create
 +   ├─ azure:containerservice:KubernetesCluster  aksCluster             create
 +   ├─ pulumi:providers:kubernetes               aksK8s                 create
 +   ├─ kubernetes:core/v1:Secret                 mongo-secrets          create
 +   └─ kubernetes:helm.sh/v2:Chart               node                   create

Diagnostics:
  pulumi:pulumi:Stack (azure-mean-azure-mean):
    Error: chart "bitnami/node" version "*" not found in https://charts.bitnami.com/bitnami repository
    (node:17424) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
    (Use `node --trace-warnings ...` to show where the warning was created)
    (node:17424) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)

    error: Error: Command failed: helm pull bitnami/node --untar --version \* --destination /var/folders/ll/yjnk2rl11xl7snrrm363084w0000gn/T/tmp-174249jmGTXOIldHs --repo https\://charts.bitnami.com/bitnami
    Error: chart "bitnami/node" version "*" not found in https://charts.bitnami.com/bitnami repository

Followed all directions, using latest versions of helm, and kubectl and pulumi cli. I have tried different versions, or just * version. I have tried pulling the same chart from azure-marketplace instead of bitnami. no luck. Any help would be appreciated.

**Comment by justinvp** [comment]
Was this addressed by https://github.com/pulumi/examples/pull/814?

**Comment by lblackstone** [comment]
From the error, it looks like `repo` is being specified both in `fetchOpts` and at the top level `.repo` field. The fix is specifying one or the other.

#814 fixed the same issue, and should hopefully make this clearer.
