### ISSUE TITLE
Incorrect description text in provisioners example?

### ISSUE THREAD

**Issue by mastoj** [pulumi/examples#828]
Is the text here correct? https://github.com/pulumi/examples/blob/8141d690013c013eb47534f8f4a1de845eda0457/azure-ts-vm-provisioners/provisioners/provisioner.ts#L6

It says it runs the first time and then continues with saying that it runs every time it changes. So what is it?

**Comment by lukehoban** [comment]
This example now uses the Command provider and so this is no longer an issue.
