### ISSUE TITLE
group getting started examples

### ISSUE THREAD

**Issue by susanev** [pulumi/examples#851]
## overview
identify which examples are the easiest to consume and use right after going through the getting started tutorial, put those in a folder named `good-first-examples` or similar

**Comment by lukehoban** [comment]
I think we (correctly) do this at the end of the getting started, and int he tutorials section in the docs.  I'm not sure we should do any explicit organization in the examples repo itself to try to optimize for this.  There are other bigger conversations on content organization which should probably be leading considerations on any reorganization in https://github.com/pulumi/examples/issues/908 and https://github.com/pulumi/examples/issues/1000.
