### ISSUE TITLE
Wait for the userData to complete

### ISSUE THREAD

**Issue by ikovac** [pulumi/examples#872]
Hello all,
Does Pulumi have a way to wait for `userData` to complete before creating another resource?
For example, CloudFormation has [creationPolicy](https://stackoverflow.com/questions/61740024/having-cloudformation-wait-for-the-user-data).

I have an ec2 instance where I install `codedeploy-agent` via userData and `codepipeline` for CI/CD pipeline. Codepipeline depends on userData.

Thanks in advance :)

**Comment by viveklak** [comment]
Unfortunately cant think of any mechanism we have currently for this. Two options:
1. Consider adding codepipeline hook in the userData script after `codedeploy-agent`
2. Use automation-api to enforce the behavior you need here.
