### ISSUE TITLE
Add test coverage of examples

### ISSUE THREAD

**Issue by lukehoban** [pulumi/examples#89]
We would like to have some automated testing in place to ensure that all examples can successfully build and deploy as we update examples and make updates to the Pulumi packages and CLI that examples depend on.

**Comment by lukehoban** [comment]
https://github.com/pulumi/examples/pull/102 added a framework for testing examples, along with integration testing coverage for two of the examples.

We'll still want to add coverage for ~all of the remaining examples here.  I'll leave this issue open to track that.

**Comment by lukehoban** [comment]
We've made good progress, but will keep working on these in 0.19.

**Comment by lukehoban** [comment]
Now that the examples will be `pulumi new`-able as part of https://github.com/pulumi/examples/pull/167, we should consider whether we can extend the test framework to run tests based on a `pulumi new` flow instead of a `pulumi stack init` flow.  This would allow us to test the config defined in the `Pulumi.yaml` files instead of repeating it in the `test.go` harness.

**Comment by lukehoban** [comment]
Cyrus to enumerate set that is left.  Decide which can be in scope for this milestone.

**Comment by CyrusNajmabadi** [comment]
Remaining (updating as i go along):

- [ ] aws-ts-eks
- [ ] aws-ts-eks-hello-world

**Comment by CyrusNajmabadi** [comment]
Major need here is EKS testing.  Assigning over to Alex.

**Comment by stack72** [comment]
When I get the GCP tests configured in CI, I am going to close this out as a 1st pass. I will then open a fresh issue that tracks the remaining tests that we need to fix as well as the additional coverage that is needed
