### ISSUE TITLE
Check azure-nextgen coverage

### ISSUE THREAD

**Issue by leezen** [pulumi/examples#901]
Check if azure-nextgen coverage of core use cases is similar to that of pulumi-azure and create examples as necessary.

**Comment by viveklak** [comment]
The following examples don't have corresponding azure-nextgen examples:

```
azure-cs-aks-private-container-registry
azure-cs-appservice
azure-fs-appservice
azure-cs-botservice
azure-go-appservice
azure-py-appservice
azure-ts-appservice
azure-cs-cosmosapp-component
azure-ts-cosmosapp-component
azure-cs-functions-consumption
azure-cs-functions-linux-app
azure-cs-msi-keyvault-rbac
azure-py-msi-keyvault-rbac
azure-ts-msi-keyvault-rbac
azure-cs-static-website
azure-ts-static-website
azure-cs-vm-scaleset
azure-py-vm-scaleset
azure-ts-vm-scaleset
azure-cs-webserver
azure-js-webserver
azure-fs-aci
azure-fs-aks
azure-go-aks-multicluster
azure-py-aks-multicluster
azure-ts-aks-multicluster
azure-go-webserver-component
azure-py-webserver-component
azure-ts-webserver-component
azure-py-arm-template
azure-ts-arm-template
azure-py-functions-raw
azure-ts-functions-raw
azure-py-hdinsight-spark
azure-ts-hdinsight-spark
azure-ts-aks-helm
azure-ts-aks-keda
azure-ts-aks-mean
azure-ts-aks-with-diagnostics
azure-ts-api-management
azure-ts-appservice-devops
azure-ts-appservice-springboot
azure-ts-cosmosdb-logicapp
azure-ts-dynamicresource
azure-ts-serverless-url-shortener-global
azure-ts-stream-analytics
azure-ts-vm-provisioners
```

**Comment by mikhailshilkov** [comment]
Let's make sure we have examples that provision AKS, AppService, CosmosDB, Function App, KeyVault, Static Website, VM (or VS scale set), and a SQL Server - in any combination - for all languages (not feeling strong about Go, don't care about JS). Bonus for more meaningful examples like URL shortener or cosmos app.

**Comment by leezen** [comment]
@mikhailshilkov I assume by "don't care about JS" you mean have TS, but not necessarily JS, right?

**Comment by mikhailshilkov** [comment]
@leezen Yes, exactly

**Comment by viveklak** [comment]
Thanks @mikhailshilkov. Thoughts on F# examples? Sounds like they were mostly community contributions.

**Comment by mikhailshilkov** [comment]
I can contribute a couple of F# examples once C# is done.

**Comment by viveklak** [comment]
- [ ] App Service https://github.com/pulumi/examples/pull/911
  - [ ] azure-cs-appservice
  - [ ] azure-ts-appservice
  - [ ] azure-py-appservice
  - [ ] azure-go-appservice
  - [ ] azure-fs-appservice
  - [ ] azure-ts-appservice-devops
  - [ ] azure-ts-appservice-springboot

- [ ] AKS
  - [ ] azure-cs-aks-private-container-registry
  - [ ] azure-go-aks-multicluster
  - [ ] azure-py-aks-multicluster
  - [ ] azure-ts-aks-multicluster
  - [ ] azure-ts-aks-helm
  - [ ] azure-ts-aks-keda
  - [ ] azure-ts-aks-mean
  - [ ] azure-ts-aks-with-diagnostics
  - [ ] azure-fs-aks

- [ ] Key Vault
  - [ ] azure-cs-msi-keyvault-rbac
  - [ ] azure-py-msi-keyvault-rbac
  - [ ] azure-ts-msi-keyvault-rbac

VM Scaleset
azure-cs-vm-scaleset
azure-py-vm-scaleset
azure-ts-vm-scaleset

Static Website
azure-cs-static-website
azure-ts-static-website

Cosmos
azure-cs-cosmosapp-component
azure-ts-cosmosapp-component
azure-cs-functions-consumption
azure-cs-functions-linux-app
azure-ts-cosmosdb-logicapp

Functions
azure-py-functions-raw
azure-ts-functions-raw

Example Apps
azure-ts-serverless-url-shortener-global

azure-cs-botservice

Web server
azure-cs-webserver
azure-js-webserver
azure-go-webserver-component
azure-py-webserver-component
azure-ts-webserver-component

Others
azure-fs-aci
azure-py-arm-template
azure-ts-arm-template
azure-py-hdinsight-spark
azure-ts-hdinsight-spark
azure-ts-api-management
azure-ts-dynamicresource
azure-ts-stream-analytics
azure-ts-vm-provisioners

**Comment by leezen** [comment]
I think we're fairly comfortable with the set we have after we've swapped the native provider to be the default, so I'll close this issue.
