### ISSUE TITLE
azure-nextgen-cs-net5-aks-webapp compiler error

### ISSUE THREAD

**Issue by StevenTCramer** [pulumi/examples#903]
When trying to compile the project I get the following error:

pulumi\examples\azure-nextgen-cs-net5-aks-webapp\AksCluster.cs(73,63): error CS0029: Cannot implicitly convert type 'string' to 'Pulumi.Input<Pulumi.AzureNextGen.ContainerService.Latest.ResourceIdentityType>'

We probably should add a global.json that requires dotnet 5 or above as well.

**Comment by mikhailshilkov** [comment]
Thank you for reporting this. I'll fix this (unless you want to create a PR?)

> We probably should add a global.json that requires dotnet 5 or above as well.

Why?

**Comment by StevenTCramer** [comment]
Cool thanks for the fix.  And the reason to include global.json is that this particular example is for dotnet 5.  So if someone has a global.json set for something different (I still have my default on 3.1) they won't get the right sdk without adding a global.json in this folder.
