### ISSUE TITLE
AzureNative function doesn't create as the classic example

### ISSUE THREAD

**Issue by martinjt** [pulumi/examples#926]
## Expected behavior
AzureNative c# functions example should be the same as the Classic

## Current behavior
The Azure Function c# example creates a function using the WebApp type, however this omits the AzureWebJobsStorage elements of an Azure function which is vitally important to a lot of functions usecases (host keys for one) and therefore causes weird issues for users.

## Steps to reproduce
Run in the example and try to create function keys in the portal.

## Context (Environment)
I'm having to now workout how to extract account keys from a `StorageAccount` resource in order to add the account keys.

## Affected feature
Creating Azure Functions through Pulumi

**Comment by viveklak** [comment]
@martinjt Just added the AzureWebJobsStorage option to the example. Could you elaborate on what issues this was causing users? A more advanced usecase is available here for reference: https://github.com/pulumi/examples/blob/master/azure-cs-credential-rotation-one-set

**Comment by martinjt** [comment]
The specific issue was generating function keys, but this manifested by not being able to add the function to an API Management instance through the UI (as under the hood it creates a function key for API management to use).

**Comment by johnkors** [comment]
The sample also fails on Windows containers and .NET functions: 

https://github.com/pulumi/examples/blob/978d32b2833daae5e6192da0eb85eb545706b826/azure-cs-functions/FunctionsStack.cs#L58

```
Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="failed to compute archive hash: couldn't read archive path '.functions': stat functions: no such file or directory", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1614950820.099221000","description":"Error received from peer ipv4:127.0.0.1:55143","file":"/tmpfs/src/github/grpc/workspace_csharp_ext_macos_x64/src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"failed to compute archive hash: couldn't read archive path 'functions': stat functions: no such file or directory","grpc_status":2}")
       at Pulumi.GrpcMonitor.RegisterResourceAsync(Resource resource, RegisterResourceRequest request)
       at Pulumi.Deployment.RegisterResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.ReadOrRegisterResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.CompleteResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options, ImmutableDictionary`2 completionSources)

```

**Comment by johnkors** [comment]
I see now that Azure Functions running on Windows should _not_ use a code blob 

[Source](https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#enabling-functions-to-run-from-a-package): 
>When running a function app on Windows, the external URL option yields worse cold-start performance. When deploying your function app to Windows, you should set WEBSITE_RUN_FROM_PACKAGE to 1 and publish with zip deployment.

Could you provide a sample for the Windows scenario as well?

**Comment by viveklak** [comment]
> Could you provide a sample for the Windows scenario as well?
Good point - tracked here: https://github.com/pulumi/examples/issues/934. Will add one shortly.
