### ISSUE TITLE
The example is out of date

### ISSUE THREAD

**Issue by luxcn** [pulumi/examples#94]

**Comment by ericrudder** [comment]
Can you be a little more specific?  Thanks!

**Comment by luxcn** [comment]
kubernetes.Service => k8s.core.v1.Service
kubernetes.Deployment => k8s.apps.v1.Deployment
[ref:https://github.com/pulumi/pulumi-kubernetes/blob/master/examples/guestbook/index.ts](https://github.com/pulumi/pulumi-kubernetes/blob/master/examples/guestbook/index.ts)

**Comment by luxcn** [comment]
Thanks!

**Comment by joeduffy** [comment]
Is it possible this got fixed already, @hausdorff?  Looking at the example, I see `k8s.*`...

**Comment by lukehoban** [comment]
I think the link above is wrong - the example that needs updating is: https://github.com/pulumi/examples/blob/master/kubernetes-ts-guestbook/index.ts

**Comment by hausdorff** [comment]
@joeduffy, @lukehoban Fixing now. :)

**Comment by hausdorff** [comment]
@joeduffy @lukehoban fixed in #98.
