### ISSUE TITLE
Serverless REST API link broken

### ISSUE THREAD

**Issue by losalamosal** [pulumi/examples#95]
In the `README` file, under Cloud Applications, the Serverless REST API link is broken.

**Comment by ericrudder** [comment]
Hi ... thanks for the report.  

Are you talking about this readme:    https://github.com/pulumi/examples/tree/master/cloud-js-api

That links correctly to https://pulumi.io/quickstart/aws-rest-api.html for me.

If there's another cloud application, with a broken link, please let us know.

**Comment by losalamosal** [comment]
Sorry for the confusion. The main `README.md` in the examples repo:

https://github.com/pulumi/examples/blob/master/README.md

Under the heading **Cloud Applications** the *Serverless REST API* link is broken.

**Comment by ericrudder** [comment]
Thanks ... this was caused by a rename.  This readme now links to https://github.com/pulumi/examples/tree/master/cloud-js-api as it should.
