### ISSUE TITLE
kind='Linux' deploys 'Windows' app service plan

### ISSUE THREAD

**Issue by brgsstm** [pulumi/examples#975]
examples/azure-py-appservice/

## Expected behavior
Expecting a Linux App Service Plan

## Current behavior
App service plan displays as 'Linux App' (top left of screen shot) but Operating System showing as 'Windows'

## Steps to reproduce
deploy examples/azure-py-appservice/ changing kind of web.AppServicePlan to 'Linux'
<img width="1357" alt="Screenshot 2021-04-20 at 19 35 45" src="https://user-images.githubusercontent.com/36605761/115447275-365a5c00-a210-11eb-9a0c-921d6c12c3b3.png">

**Comment by mikhailshilkov** [comment]
Where in that example do we configure it to be Linux?

**Comment by mikhailshilkov** [comment]
The following change

```py
app_service_plan = web.AppServicePlan(
    "appservice-asp",
    resource_group_name=resource_group.name,
    kind="Linux",
    reserved=True,
    sku=web.SkuDescriptionArgs(
        tier="Basic",
        name="B1",
    ))
```

makes it 

![image](https://user-images.githubusercontent.com/1454008/115556128-9c96bb80-a2b0-11eb-95f8-fdda8bed677d.png)

**Comment by brgsstm** [comment]
Thanks and granted not the best place to post this, I meant to post against pulumi-azure-native. 'reserved=True' was the missing puzzle piece...
